# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=140)),
                ('student_id', models.CharField(max_length=10)),
                ('student_email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=50)),
                ('assignment', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('file_title', models.CharField(max_length=140)),
                ('file_type', models.CharField(max_length=50)),
                ('file_content', models.FileField(upload_to='')),
                ('file_version', models.CharField(max_length=10)),
                ('grade', models.IntegerField()),
            ],
        ),
    ]
